#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST: vvtest

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import time
import glob

import vvtestutils as vtu
import testutils as util


class suite( vtu.vvtestTestCase ):

    def test_magic(self):
        ""
        util.writefile( "atest.vvt", """
            pass
            """ )

        vtu.runvvtest( '-G 1' )

        assert os.path.isfile( 'testlist.1' )
        assert len( glob.glob('testlist*') ) == 1
        assert len( glob.glob('TestResults*') ) == 0


########################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
