#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST: vvtest

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
from os.path import abspath

import vvtestutils as vtu
import testutils as util

from vvtestutils import windows, not_windows


class script_tests( vtu.vvtestTestCase ):

    @not_windows
    def test_an_executable_script_as_a_test_file(self):
        ""
        util.writescript( 'hello.vvt', """
            #!/bin/sh
            echo "hello from the hello test script"
            """ )

        vrun = vtu.runvvtest()
        vrun.assertCounts( total=1, npass=1 )
        assert vrun.getTestIds() == [ 'hello' ]
        assert vrun.countGrepLogs( 'hello from the hello test script' ) == 1

    def test_that_the_test_name_can_be_different_than_the_script_name(self):
        ""
        util.writefile( 'hello.vvt', """
            #VVT: name=world
            print ( "hello from the hello/world test script" )
            """ )
        util.writefile( 'namerr1.vvt', """
            #VVT: name (foo=bar) = world
            assert False
            """ )
        util.writefile( 'namerr2.vvt', """
            #VVT: name = world mars
            assert False
            """ )

        vrun = vtu.runvvtest()
        vrun.assertCounts( total=1, npass=1 )

        assert vrun.getTestIds() == [ 'world' ]
        assert vrun.countGrepLogs( 'hello from the hello/world test script' ) == 1

        assert vrun.countLines( 'skipping *namerr1.vvt*no attr' ) == 1
        assert vrun.countLines( 'skipping *namerr2.vvt*invalid' ) == 1

    def test_that_python_is_always_used_to_run_non_executable_scripts(self):
        ""
        util.writefile( 'hello.vvt',
            "#!/bin/sh\n" + \
            "print ( 'hello from the hello test script' )\n" )

        vrun = vtu.runvvtest()
        vrun.assertCounts( total=1, npass=1 )
        assert vrun.getTestIds() == [ 'hello' ]
        assert vrun.countGrepLogs( 'hello from the hello test script' ) == 1

    def test_variables_in_the_vvtest_util_file(self):
        ""
        os.mkdir( 'bin' )

        util.writefile( 'atest.vvt', """
            #VVT: keywords : something borrowed
            import os, sys
            print ( "hello from the python test script" )
            import vvtest_util as vvt
            print ( 'hello, dir=', dir(vvt) )

            assert hasattr( vvt, 'NAME' )
            assert hasattr( vvt, 'TESTID' )
            assert hasattr( vvt, 'PLATFORM' )
            assert hasattr( vvt, 'COMPILER' )
            assert hasattr( vvt, 'VVTESTSRC' )
            assert hasattr( vvt, 'CONFIGDIR' )
            assert hasattr( vvt, 'PROJECT' )
            assert hasattr( vvt, 'OPTIONS' )
            assert hasattr( vvt, 'OPTIONS_OFF' )
            assert hasattr( vvt, 'SRCDIR' )

            assert vvt.NAME == 'atest'
            assert os.path.samefile( vvt.PROJECT, '"""+abspath('bin')+"""' )
            assert vvt.OPTIONS == ['dbg']
            assert set(vvt.KEYWORDS) == set(['something','borrowed'])
            """ )

        for batch in [False,True]:

            vtu.remove_results()

            vrun = vtu.runvvtest( '-j bin -o dbg', batch=batch )
            vrun.assertCounts( total=1, npass=1 )
            assert vrun.getTestIds() == [ 'atest' ]
            assert vrun.countGrepLogs( 'hello from the python test script' ) == 1

    def test_a_python_test_that_exits_with_a_diff_a_pass_and_a_fail(self):
        ""
        util.write_py_script( 'tpass.vvt', """
            import os, sys
            import vvtest_util as vvt
            """ )
        util.write_py_script( 'tdiff.vvt', """
            import sys
            import vvtest_util as vvt
            sys.exit( vvt.diff_exit_status )
            """ )
        util.write_py_script( 'tfail.vvt', """
            import os, sys
            def myfunc():
                raise Exception( "test failed" )
            myfunc()
            """ )

        for batch in [False,True]:

            vtu.remove_results()

            vrun = vtu.runvvtest( batch=batch )
            vrun.assertCounts( total=3, npass=1, diff=1, fail=1 )

    def test_multiple_tests_in_one_script_file(self):
        ""
        util.write_py_script( 'multi.vvt', """
            #VVT: name=multi
            #VVT: name=multi2
            import vvtest_util as vvt
            print ( "hello from the "+vvt.NAME+" test" )
            """ )

        for batch in [False,True]:

            vtu.remove_results()

            vrun = vtu.runvvtest( batch=batch )
            vrun.assertCounts( total=2, npass=2 )

            assert vrun.getTestIds() == [ 'multi', 'multi2' ]

            assert vrun.countGrepLogs( 'hello from the multi test' ) == 1
            assert vrun.countGrepLogs( 'hello from the multi2 test' ) == 1

    def test_copy_and_link_files_specification(self):
        ""
        util.writefile( 'file1.txt', """
            this is file one
            """ )
        util.writefile( 'file2.txt', """
            this is file two
            """ )
        util.writefile( 'file3.txt', """
            this is file three
            """ )
        util.write_py_script( 'files.vvt', """
            #VVT: link : file1.txt file2.txt
            #VVT: copy : file3.txt
            #VVT: link (rename) : file1.txt, lfile1 file2.txt,lfile2
            #VVT: copy (rename) : file3.txt ,cfile3
            import os
            assert os.path.exists( 'file1.txt' )
            assert os.path.islink( 'file1.txt' )
            assert os.path.exists( 'file2.txt' )
            assert os.path.islink( 'file2.txt' )
            assert os.path.exists( 'file3.txt' )
            assert not os.path.islink( 'file3.txt' )
            assert os.path.exists( 'lfile1' )
            assert os.path.islink( 'lfile1' )
            assert os.path.exists( 'lfile2' )
            assert os.path.islink( 'lfile2' )
            assert os.path.exists( 'cfile3' )
            assert not os.path.islink( 'cfile3' )

            import filecmp
            assert filecmp.cmp( 'file1.txt', 'lfile1', shallow=False )
            assert filecmp.cmp( 'file2.txt', 'lfile2', shallow=False )
            assert filecmp.cmp( 'file3.txt', 'cfile3', shallow=False )
            """ )

        for batch in [False,True]:

            vtu.remove_results()

            vrun = vtu.runvvtest( batch=batch )
            vrun.assertCounts( total=1, npass=1 )

    def test_copy_and_link_files_with_attribute_specifications(self):
        ""
        platname = vtu.core_platform_name()

        util.writefile( 'file1.txt', """
            this is file one
            """ )
        util.writefile( 'file2.txt', """
            this is file two
            """ )
        util.writefile( 'file3.txt', """
            this is file three
            """ )
        util.writefile( 'file4.txt', """
            this is file four
            """ )
        util.writefile( 'file5.txt', """
            this is file five
            """ )
        util.write_py_script( 'files.vvt', """
            #VVT: name = files
            #VVT: name = another
            #VVT: link (testname=files): file1.txt
            #VVT: link (testname=not files): file2.txt
            #VVT: copy (options=dbg, testname=another) : file3.txt
            #VVT: link (rename, platforms="Junk") : file4.txt, lfile4
            #VVT: copy (rename, platforms="""+platname+""") : file5.txt,cfile5
            
            import os
            import vvtest_util as vvt
            if vvt.NAME == 'files':
                assert os.path.exists( 'file1.txt' )
                assert os.path.islink( 'file1.txt' )
                assert not os.path.exists( 'file2.txt' )
            else:
                assert os.path.exists( 'file2.txt' )
                assert os.path.islink( 'file2.txt' )
            if 'dbg' in vvt.OPTIONS and vvt.NAME == 'another':
                assert os.path.exists( 'file3.txt' )
                assert not os.path.islink( 'file3.txt' )
            else:
                assert not os.path.exists( 'file3.txt' )
            assert not os.path.exists( 'file4.txt' )
            assert not os.path.exists( 'lfile4' )
            assert os.path.exists( 'cfile5' )
            assert not os.path.islink( 'cfile5' )
            """ )

        for batch in [False,True]:

            vtu.remove_results()

            vrun = vtu.runvvtest( batch=batch )
            vrun.assertCounts( total=2, npass=2 )

            vtu.remove_results()

            vrun = vtu.runvvtest( '-o dbg', batch=batch )
            vrun.assertCounts( total=2, npass=2 )

            fn = util.globfile( 'TestResults*/another/file3.txt' )
            assert not os.path.islink( fn )


########################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
