#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import time

import vvtestutils as vtu
import testutils as util


class test_arguments( vtu.vvtestTestCase ):

    def test_use_command_line_option_to_add_test_script_options(self):
        ""
        util.writefile( 'atest.vvt', """
            #VVT: parameterize : planet=earth mars
            import sys
            print ( 'script args '+' '.join( sys.argv[1:] ) )
            """ )

        testargs = '--test-args=--dummy --test-args=foo'

        for batch in [False,True]:

            vtu.remove_results()

            vrun = vtu.runvvtest( testargs, batch=batch )
            vrun.assertCounts( total=2, npass=2 )
            assert vrun.getTestIds() == [ 'atest.planet=earth',
                                          'atest.planet=mars' ]

            assert vrun.countGrepLogs( 'script args *--dummy *foo' ) == 2

            tdir = vrun.resultsDir()

            vrun = vtu.runvvtest( testargs, '-R -p nx=4/planet=earth',
                                  batch=batch, chdir=tdir )
            vrun.assertCounts( total=1, npass=1 )

            assert vrun.getTestIds() == [ 'atest.planet=earth' ]

            assert vrun.countGrepLogs( 'script args *--dummy *foo' ) == 2


########################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
