#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import time

import vvtestutils as vtu
import testutils as util


class trig_utility_tests( vtu.vvtestTestCase ):

    def test_a_file_from_the_libvvtest_dir_can_be_imported(self):
        """
        when the trig directory goes away, this test should instead pick up
        perms.py from libvvtest; in that case, no sys.path manipulation is
        needed because the top level directory of vvtest is already there
        """
        util.writefile( 'atest.vvt', """
            import sys
            import vvtest_util as vvt
            import libvvtest.perms as perms
            print ( 'USRNAME='+str(perms.my_user_name()) )
            """ )

        vrun = vtu.runvvtest()
        vrun.assertCounts( total=1, npass=1 )

        assert len( vrun.greplogs( 'USRNAME=' ) ) == 1


########################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
